### ISSUE TITLE
RSpec says yahtzee_bonus doesn't exist

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#10]
![image](https://cloud.githubusercontent.com/assets/7078074/5369674/4f21aca6-7fcc-11e4-96a0-9c1429dcc885.png)

**Comment by Zrp200** [comment]
I removed the method

**Comment by Zrp200** [comment]
So much for yahtzee bonus....

**Comment by martimatix** [comment]
Different Yahtzee games handle additional Yahtzees differently. I propose that in this game any additional Yahtzees can be allocated to the Yahtzee field and you get double the points each time. In other words, the first Yahtzee is worth 50 points, the next is worth 100 (subtotal 150), the next is worth 200 (subtotal 350), the next is worth 400 (subtotal 750) and so on. However, if a non-Yahtzee is allocated to the blank score field, that field can no longer be used.

**Comment by Zrp200** [comment]
Removed Yahtzee Bonus branch because it was unable to merge in or out

**Comment by martimatix** [comment]
Yahtzee bonus implemented for now.
