### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#11]
I know how to get the library tested after every commit

**Comment by Zrp200** [comment]
I usually set it up as soon as I make a repo but I can't set it up here since I'm not the owner.

**Comment by martimatix** [comment]
Is there something I can do on my end to get this working?

**Comment by Zrp200** [comment]
1. Sign up at www.travis-ci.org
2. Add this repository

I have already set up the rest. It will send you an email whenever a test has failed

**Comment by Zrp200** [comment]
After it's set up, I will make it deploy to rubygems after we finish

**Comment by Zrp200** [comment]
There is also CodeClimate......

**Comment by Zrp200** [comment]
It can be allowed to create issues

**Comment by Zrp200** [comment]
There is a service hook for Travis-CI

**Comment by Zrp200** [comment]
Its not working at the moment without the hook

**Comment by martimatix** [comment]
I will look into this tonight after work. (~10 hours after this message's time stamp)

**Comment by martimatix** [comment]
I went to Travis CI and added the Ruby-Dice repository. What do I need to do for the service hook?

**Comment by martimatix** [comment]
Is there any action I need to take re: CodeClimate?

**Comment by Zrp200** [comment]
Travis CI is working

**Comment by Zrp200** [comment]
CodeClimate Test Coverage:
1. [Log in (The link will log you in)](https://codeclimate.com/login/github)
2. Go to [This repo](https://codeclimate.com/github/martimatix/Ruby-Dice)
3. Click on `Settings`
4. Click on `Test Coverage`
5. Copy the Environment Variable on the page to [Travis CI](https://travis-ci.org/martimatix/Ruby-Dice/settings/env_vars)

**Comment by martimatix** [comment]
Done.

**Comment by Zrp200** [comment]
Did you add `bundle exec rspec` to the end of the CodeClimate environment variable?

**Comment by martimatix** [comment]
Done.

**Comment by Zrp200** [comment]
Coverage is working
