### ISSUE TITLE
Fixnum and rspec failiures

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#15]
Why is rspec returning a list of failiures with Fixnum? What is Fixnum?

**Comment by Zrp200** [comment]
`Fixnum` is a subclass of `Integer`, referring to small numbers. Should I change it to `Integer`?

**Comment by martimatix** [comment]
Keep Fixnum. What needs to be done so that rspec no longer returns errors relating to fixnum?

**Comment by Zrp200** [comment]
The return values need to be numbers and not nil.
