### ISSUE TITLE
ScoreSheet.to_s

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#19]
Zachary, can you write the to_s method for the `ScoreSheet` class? Expected output should look something like this:

```
============================= S C O R E  S H E E T =============================


        UPPER SCORE (19)        LOWER SCORE (55)
        Ones    1           Three of a Kind -
        Twos    -           Four of a Kind  -
        Threes  6           Full House  25
        Fours   12          Small Straight  30
        Fives   -           Large Straight  -
        Sixes   -           Chance      -
        Bonus   0           Yahtzee     -

                                   TOTAL = 74                                   

================================================================================
```

The above output is just a suggestion. In fact, it doesn't look that good because it's not centred correctly and the alignment is off.

I've put a "hello world!" in the method but this needs to be removed and replaced.

**Comment by Zrp200** [comment]
On it. I've done that kind of thing before

**Comment by Zrp200** [comment]
Give me dimensions

**Comment by martimatix** [comment]
Assume width of 80 characters.

**Comment by Zrp200** [comment]
Let me try to get it working first

**Comment by Zrp200** [comment]
Finished. It may be off center and just used tabs to separate items. Didn't have time for dimensions

**Comment by martimatix** [comment]
:+1: Good job. We can always clean up the formatting later.

**Comment by Zrp200** [comment]
Build keeps getting errors from this method. This may also be what is preventing Code Climate  from working. Will fix

**Comment by Zrp200** [comment]
This had no effect on the build

**Comment by Zrp200** [comment]
other than runtime
