### ISSUE TITLE
Code Climate help

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#21]
Whenever I run rspec, I get the following message at the top of the report: `Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.`

Where exactly do I set `ENV['CODECLIMATE_REPO_TOKEN']`?

**Comment by Zrp200** [comment]
It says `401 Error`

**Comment by Zrp200** [comment]
Will look into it

**Comment by Zrp200** [comment]
I opened an issue with Code Climate

**Comment by Zrp200** [comment]
I don't know why this is happening

**Comment by martimatix** [comment]
Ok. It's not a critical issue. Closing for now.

**Comment by Zrp200** [comment]
You could just set it up again, especially since I accidently deleted the variable value :wink:
Just insert the value from #11 into the `VALUE` field of the env variable `CODECLIMATE_REPO_TOKEN` in Travis CI

**Comment by martimatix** [comment]
Just did the steps from #11 again but no change. Appears to be a local issue.

**Comment by Zrp200** [comment]
Works!!!!
