### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#22]
dba87e024e62c950e1ecc693aa6a0e7bc65271ce

**Comment by martimatix** [comment]
Leading zero should be replaced with a space because `9` is easier to read than `09`.

Could we do away with the entire `double_digit` method and just use `rjust`?

Click on link below for more info.
http://stackoverflow.com/questions/15021261/how-to-align-ruby-string-to-left-or-right

**Comment by Zrp200** [comment]
How about you implement it?

**Comment by martimatix** [comment]
No problem. Leave it to me.

**Comment by Zrp200** [comment]
Thanks

**Comment by martimatix** [comment]
Had a go at the `to_s` command. It's incomplete and need to work on alignment.

**Comment by martimatix** [comment]
Alignment fixed.
