### ISSUE TITLE
Code Climate issues

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#27]
I am getting sick of manually opening issues whenever Code Climate finds something wrong with the code, so here is how to make it automatically open issues:
1. Go to https://github.com/settings/applications
2. Click on [Generate New Token](https://github.com/settings/tokens/new)
3. Enter 'Issue Tracking' in the description (It really doesn't matter)
4. Give it appropriate permissions so it can work correctly; I just gave it everything just in case
5. Create it and copy the code
6. Go to [Code Climate](https://codeclimate.com/github/martimatix/Ruby-Dice)
7. Hit `Settings`
8. Click on Integrations
9. Click on `Set up` next to `Github Issues`
10. Paste the code into the first field
11. Type in `martimatix/Ruby-Dice` in the second field
12. Type in `Code Climate` into the third field

**Comment by martimatix** [comment]
Done.

That was a very easy to follow guide. Thanks.
