### ISSUE TITLE
ScoreSheet

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#3]

**Comment by Zrp200** [comment]
I don't know what to test for in the code. I will look at it more closely tonight.

**Comment by martimatix** [comment]
The score calculators should be tested with some dice values and their expected outputs.

eg: Test for `full_house([1, 1, 1, 2, 2]) == 25`

I might break up `enter_score()` into smaller methods to make testing easier.

**Comment by Zrp200** [comment]
Should a FiveDice object be initialized with ScoreSheet.new? It would make testing much easier

**Comment by martimatix** [comment]
Good idea. Make it so.

**Comment by Zrp200** [comment]
Doing

**Comment by Zrp200** [comment]
done

**Comment by Zrp200** [comment]
I put it into a different branch that is ready to merge

**Comment by Zrp200** [comment]
Merged

**Comment by Zrp200** [comment]
I've added a lot of tests to [spec/lib/score_sheet_spec.rb](https://github.com/martimatix/Ruby-Dice/blob/master/spec/lib/score_sheet_spec.rb)
