### ISSUE TITLE
Field Shortcuts

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#32]
There needs to be abbreviations for the score field

**Comment by martimatix** [comment]
Let's just borrow the short cuts from [this](https://github.com/nickb/yahtzee) repo.

``` ruby
key_move_mappings = {"1" => :ones, "2" => :twos, "3" => :threes,
    "4" => :fours, "5" => :fives, "6" => :sixes,
    "s" => :small_straight, "l" => :large_straight,
    "t" => :three_of_a_kind, "f" => :four_of_a_kind,
    "h" => :full_house, "y" => :yahtzee, "?" => :chance};
```

I had initially envisioned typing the full name but supporting tab completion. However, that's probably more work than necessary.

**Comment by Zrp200** [comment]
Sure

**Comment by Zrp200** [comment]
Where should this go?

**Comment by martimatix** [comment]
In the `Player` class.
