### ISSUE TITLE
gets.chomp

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#34]
In my experience, `gets` should only be used in executables. I've seen it ruin my programs before.

**Comment by martimatix** [comment]
What's the alternative?

**Comment by Zrp200** [comment]
Remove it from the library and put it into the executable as a `Proc` or `lambda`

**Comment by Zrp200** [comment]
If anything is in `ARGV` when `gets` is executed, the value in `ARGV` will be used instead of prompting the user

**Comment by Zrp200** [comment]
It can be addressed later
