### ISSUE TITLE
Refactor ScoreSheet from a C on Code Climate

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#36]
https://codeclimate.com/github/martimatix/Ruby-Dice/ScoreSheet

**Comment by martimatix** [comment]
One way to do this would be to move the score calculators into a module. However, I don't think it's worth the effort.

**Comment by Zrp200** [comment]
I'll work on it

**Comment by Zrp200** [comment]
What methods should be moved over?

**Comment by martimatix** [comment]
All the score calculators and helper methods associated with score calculations.

This will be a **lot** of work and tests will have to be moved around as well. Expect things to break.

**Comment by Zrp200** [comment]
I am going to do this in another branch

**Comment by Zrp200** [comment]
Tests say that `ones` don't exist. Am I doing something wrong?

**Comment by Zrp200** [comment]
Can you take a look at the branch?

**Comment by martimatix** [comment]
Currently not on a computer with Ruby but the test looks fine. I'm quite impressed that you did this so quickly.

**Comment by Zrp200** [comment]
Thank you
