### ISSUE TITLE
Require vs Require_relative

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#42]
When `require_relative` is changed to `require`, I get errors. It has something to do with `require` not looking in the `Ruby-Dice` directory. What am I missing here?

**Comment by Zrp200** [comment]
Its hard to explain. I use `require_relative` for files in the same directory. The library is downloaded during the build and after compilation, so you can simply require a library file as if it was built into Ruby, in some cases.

**Comment by Zrp200** [comment]
Unfortunately, it discourages manual testing

**Comment by martimatix** [comment]
If I enter `$ ruby bin/Ruby-Dice.rb` in my terminal, I'm getting an error. My ruby interpreter is not looking in the `lib` folder. Any ideas about what I can do about this?

**Comment by Zrp200** [comment]
You can manually compile the code. The resulting files will ignored when you push to the repository. Unfortunately, you will have to do this every time you update the repository 
1. `gem build Ruby-Dice.gemspec`
2. `gem install Ruby-Dice-0.0.0.pre.gem`
Note: After this is completed, you can call the executable by typing `Ruby-Dice` in terminal
