### ISSUE TITLE
enter_score not passing in rspec

### ISSUE THREAD

**Issue by martimatix** [martimatix/Ruby_Dice#47]
Manual testing shows that `enter_score` behaves as expected but the tests aren't passing in rspec.

**Comment by Zrp200** [comment]
I think it is because the methods are in Scoring, but that doesn't make any sense... I just looked for a minute, and I will take another later

**Comment by martimatix** [comment]
It turns out that the issue had to do with the nuances of `extend` and `include`. The `send` method seems to work happily with an object but not with a module.

Although I didn't try it, it seems that if you [alias each function in the module with `module_function`](http://stackoverflow.com/a/322515/2801759), things could have worked as per the previous commit.

Things are looking good again in adc65de000f21cc3f4b76bb4b025a27224cff86f but now the `yahtzee` method is failing tests. In addition, things are looking a bit clunky with the `Scoring` module being wrapped in the `Calculator` class. This is a better position than the previous commit.

Code Climate has given A grades to `scoring.rb` and `scoresheet.rb`. :sunglasses:

**Comment by Zrp200** [comment]
I heard that `send` breaks some programming rule

On Tue, Dec 23, 2014 at 10:29 PM, Mario Martinez notifications@github.com
wrote:

> It turns out that the issue had to do with the nuances of extend and
> include. The send method seems to work happily with an object but not
> with a module.
> 
> Although I didn't try it, it seems that if you alias each function in the
> module with module_function http://stackoverflow.com/a/322515/2801759,
> things could have worked as per the previous commit.
> 
> Things are looking good again in adc65de
> https://github.com/martimatix/Ruby-Dice/commit/adc65de000f21cc3f4b76bb4b025a27224cff86f
> but now the yahtzee method is failing tests. In addition, things are
> looking a bit clunky with the Scoring module being wrapped in the
> Calculator class. This is a better position than the previous commit.
> 
> Code Climate has given A grades to scoring.rb and scoresheet.rb. [image:
> :sunglasses:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/martimatix/Ruby-Dice/issues/47#issuecomment-68030342.

## 

_Zachary Perlmutter_

**Comment by Zrp200** [comment]
I had `ScoreSheet` `extend` _and_ `include` `Scoring` to replace `Calculator` while breaking a few things.

**Comment by Zrp200** [comment]
Why not have it inherit from Scoring?

**Comment by martimatix** [comment]
Issue resolved by moving the arrays `UpperScores` and `LowerScores` from `scoring.rb` to `scoresheet.rb`. `extend scoring` no longer required.
