### ISSUE TITLE
RubyGems

### ISSUE THREAD

**Issue by Zrp200** [martimatix/Ruby_Dice#51]

**Comment by Zrp200** [comment]
Can't release it unless I decide to fork it

**Comment by Zrp200** [comment]
Do you have a RubyGems account?

**Comment by Zrp200** [comment]
I am pretty sure this works:
1. [Create an account on `RubyGems` if you don't have one.](http://rubygems.org/sign_up)
2. Go to Terminal
3. Type in `gem build Ruby-Dice.gemspec`
4. Type in `gem push Ruby-Dice-0.0.0.gem`

**Comment by martimatix** [comment]
Is it worth releasing this despite the fact that it's still buggy and needs tweaking?

**Comment by Zrp200** [comment]
I tested it and its pretty good for a first release. How do you usually version?

**Comment by martimatix** [comment]
I don't have a versioning system. Will look into RubyGems today.

**Comment by Zrp200** [comment]
I use `Major.Minor.Patch`(`.Executable`) for application versions

**Comment by Zrp200** [comment]
If I just updated the executable, I would version it as `0.0.0.1`

**Comment by Zrp200** [comment]
Updated the version to `0.1.0`

**Comment by Zrp200** [comment]
If and when you release it to RubyGems, type in on terminal `gem owner Ruby-Dice -a zrp200@gmail.com` to add me to it

**Comment by martimatix** [comment]
I just tried this and got the following error:

```
mario@crunchbang:~/projects/Ruby-Dice$ gem push Ruby-Dice-0.0.1.gem
Pushing gem to https://rubygems.org...
Unable to change case of gem name with indexed versions
Please yank all versions first
```

Any ideas why I'm getting this error? Does it have anything to do with uppercase letters?

**Comment by Zrp200** [comment]
The first gem I ever released was capitalized

**Comment by Zrp200** [comment]
Just undid that commit

**Comment by Zrp200** [comment]
I like the name

**Comment by Zrp200** [comment]
I'm pretty sure it doesn't like the `Dice` part

**Comment by martimatix** [comment]
Any way to change that? Would `RubyDice` be any better?

**Comment by Zrp200** [comment]
if you did, I would strongly recommend that you change the name of this repo to `RubyDice` and change `Ruby-Dice` to `RubyDice` in all files

**Comment by martimatix** [comment]
That seems like a lot of work :worried: . Is there any other way to push this to RubyGems without changing the name `Ruby-Dice`?

**Comment by Zrp200** [comment]
Not that I know of. I usually did this early on in my projects :zzz:

**Comment by Zrp200** [comment]
How about `Ruby_Dice`? :sleepy:

**Comment by martimatix** [comment]
Renamed the repo to `Ruby_Dice`.

**Comment by martimatix** [comment]
You should go to sleep. :open_mouth: Deal with this later.

**Comment by Zrp200** [comment]
Switched `Ruby-Dice` to `Ruby_Dice` in _all_ files :zzz:

**Comment by martimatix** [comment]
:+1:

**Comment by martimatix** [comment]
Successfully registered gem! :grinning: (Added zrp200@gmail.com as an author)
